-- Database schema for catalog tables
-- Generated by: lake admin --dump-schema
-- This file is used to initialize test databases

CREATE TABLE IF NOT EXISTS dz_contributors_current (
    pk VARCHAR,
    code VARCHAR,
    name VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS dz_contributors_history (
    pk VARCHAR,
    code VARCHAR,
    name VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR
);

CREATE TABLE IF NOT EXISTS dz_device_iface_usage_raw (
    time TIMESTAMP,
    device_pk VARCHAR,
    host VARCHAR,
    intf VARCHAR,
    user_tunnel_id BIGINT,
    link_pk VARCHAR,
    link_side VARCHAR,
    model_name VARCHAR,
    serial_number VARCHAR,
    carrier_transitions BIGINT,
    in_broadcast_pkts BIGINT,
    in_discards BIGINT,
    in_errors BIGINT,
    in_fcs_errors BIGINT,
    in_multicast_pkts BIGINT,
    in_octets BIGINT,
    in_pkts BIGINT,
    in_unicast_pkts BIGINT,
    out_broadcast_pkts BIGINT,
    out_discards BIGINT,
    out_errors BIGINT,
    out_multicast_pkts BIGINT,
    out_octets BIGINT,
    out_pkts BIGINT,
    out_unicast_pkts BIGINT,
    carrier_transitions_delta BIGINT,
    in_broadcast_pkts_delta BIGINT,
    in_discards_delta BIGINT,
    in_errors_delta BIGINT,
    in_fcs_errors_delta BIGINT,
    in_multicast_pkts_delta BIGINT,
    in_octets_delta BIGINT,
    in_pkts_delta BIGINT,
    in_unicast_pkts_delta BIGINT,
    out_broadcast_pkts_delta BIGINT,
    out_discards_delta BIGINT,
    out_errors_delta BIGINT,
    out_multicast_pkts_delta BIGINT,
    out_octets_delta BIGINT,
    out_pkts_delta BIGINT,
    out_unicast_pkts_delta BIGINT,
    delta_duration DOUBLE
);

CREATE TABLE IF NOT EXISTS dz_device_link_latency_samples_raw (
    time TIMESTAMP,
    epoch BIGINT,
    sample_index INTEGER,
    origin_device_pk VARCHAR,
    target_device_pk VARCHAR,
    link_pk VARCHAR,
    rtt_us BIGINT,
    loss BOOLEAN,
    ipdv_us BIGINT
);

CREATE TABLE IF NOT EXISTS dz_devices_current (
    pk VARCHAR,
    status VARCHAR,
    device_type VARCHAR,
    code VARCHAR,
    public_ip VARCHAR,
    contributor_pk VARCHAR,
    metro_pk VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    max_users INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dz_devices_history (
    pk VARCHAR,
    status VARCHAR,
    device_type VARCHAR,
    code VARCHAR,
    public_ip VARCHAR,
    contributor_pk VARCHAR,
    metro_pk VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    max_users INTEGER
);

CREATE TABLE IF NOT EXISTS dz_internet_metro_latency_samples_raw (
    time TIMESTAMP,
    epoch BIGINT,
    sample_index INTEGER,
    origin_metro_pk VARCHAR,
    target_metro_pk VARCHAR,
    data_provider VARCHAR,
    rtt_us BIGINT,
    ipdv_us BIGINT
);

CREATE TABLE IF NOT EXISTS dz_links_current (
    pk VARCHAR,
    status VARCHAR,
    code VARCHAR,
    tunnel_net VARCHAR,
    contributor_pk VARCHAR,
    side_a_pk VARCHAR,
    side_z_pk VARCHAR,
    side_a_iface_name VARCHAR,
    side_z_iface_name VARCHAR,
    link_type VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    committed_rtt_ns BIGINT,
    committed_jitter_ns BIGINT,
    bandwidth_bps BIGINT,
    isis_delay_override_ns BIGINT
);

CREATE TABLE IF NOT EXISTS dz_links_history (
    pk VARCHAR,
    status VARCHAR,
    code VARCHAR,
    tunnel_net VARCHAR,
    contributor_pk VARCHAR,
    side_a_pk VARCHAR,
    side_z_pk VARCHAR,
    side_a_iface_name VARCHAR,
    side_z_iface_name VARCHAR,
    link_type VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    committed_rtt_ns BIGINT,
    committed_jitter_ns BIGINT,
    bandwidth_bps BIGINT,
    isis_delay_override_ns BIGINT
);

CREATE TABLE IF NOT EXISTS dz_metros_current (
    pk VARCHAR,
    code VARCHAR,
    name VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    longitude DOUBLE,
    latitude DOUBLE
);

CREATE TABLE IF NOT EXISTS dz_metros_history (
    pk VARCHAR,
    code VARCHAR,
    name VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    longitude DOUBLE,
    latitude DOUBLE
);

CREATE TABLE IF NOT EXISTS dz_users_current (
    pk VARCHAR,
    owner_pk VARCHAR,
    status VARCHAR,
    kind VARCHAR,
    client_ip VARCHAR,
    dz_ip VARCHAR,
    device_pk VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    tunnel_id INTEGER
);

CREATE TABLE IF NOT EXISTS dz_users_history (
    pk VARCHAR,
    owner_pk VARCHAR,
    status VARCHAR,
    kind VARCHAR,
    client_ip VARCHAR,
    dz_ip VARCHAR,
    device_pk VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    tunnel_id INTEGER
);

CREATE TABLE IF NOT EXISTS geoip_records_current (
    ip VARCHAR,
    country_code VARCHAR,
    country VARCHAR,
    region VARCHAR,
    city VARCHAR,
    metro_name VARCHAR,
    postal_code VARCHAR,
    time_zone VARCHAR,
    asn_org VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    city_id INTEGER,
    latitude DOUBLE,
    longitude DOUBLE,
    accuracy_radius INTEGER,
    asn BIGINT,
    is_anycast BOOLEAN,
    is_anonymous_proxy BOOLEAN,
    is_satellite_provider BOOLEAN
);

CREATE TABLE IF NOT EXISTS geoip_records_history (
    ip VARCHAR,
    country_code VARCHAR,
    country VARCHAR,
    region VARCHAR,
    city VARCHAR,
    metro_name VARCHAR,
    postal_code VARCHAR,
    time_zone VARCHAR,
    asn_org VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    city_id INTEGER,
    latitude DOUBLE,
    longitude DOUBLE,
    accuracy_radius INTEGER,
    asn BIGINT,
    is_anycast BOOLEAN,
    is_anonymous_proxy BOOLEAN,
    is_satellite_provider BOOLEAN
);

CREATE TABLE IF NOT EXISTS solana_block_production_raw (
    epoch INTEGER,
    time TIMESTAMP,
    leader_identity_pubkey VARCHAR,
    leader_slots_assigned_cum BIGINT,
    blocks_produced_cum BIGINT
);

CREATE TABLE IF NOT EXISTS solana_gossip_nodes_current (
    pubkey VARCHAR,
    gossip_ip VARCHAR,
    tpuquic_ip VARCHAR,
    version VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    epoch BIGINT,
    gossip_port INTEGER,
    tpuquic_port INTEGER
);

CREATE TABLE IF NOT EXISTS solana_gossip_nodes_history (
    pubkey VARCHAR,
    gossip_ip VARCHAR,
    tpuquic_ip VARCHAR,
    version VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    epoch BIGINT,
    gossip_port INTEGER,
    tpuquic_port INTEGER
);

CREATE TABLE IF NOT EXISTS solana_leader_schedule_current (
    node_pubkey VARCHAR,
    slots VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    epoch BIGINT,
    slot_count BIGINT
);

CREATE TABLE IF NOT EXISTS solana_leader_schedule_history (
    node_pubkey VARCHAR,
    slots VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    epoch BIGINT,
    slot_count BIGINT
);

CREATE TABLE IF NOT EXISTS solana_vote_account_activity_raw (
    time TIMESTAMP,
    vote_account_pubkey VARCHAR,
    node_identity_pubkey VARCHAR,
    root_slot BIGINT,
    last_vote_slot BIGINT,
    cluster_slot BIGINT,
    is_delinquent BOOLEAN,
    epoch_credits_json VARCHAR,
    credits_epoch INTEGER,
    credits_epoch_credits BIGINT,
    credits_delta BIGINT,
    activated_stake_lamports BIGINT,
    activated_stake_sol DOUBLE,
    commission INTEGER,
    collector_run_id VARCHAR
);

CREATE TABLE IF NOT EXISTS solana_vote_accounts_current (
    vote_pubkey VARCHAR,
    node_pubkey VARCHAR,
    epoch_vote_account VARCHAR,
    as_of_ts TIMESTAMP NOT NULL,
    row_hash VARCHAR NOT NULL,
    epoch BIGINT,
    activated_stake_lamports BIGINT,
    commission_percentage BIGINT
);

CREATE TABLE IF NOT EXISTS solana_vote_accounts_history (
    vote_pubkey VARCHAR,
    node_pubkey VARCHAR,
    epoch_vote_account VARCHAR,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    row_hash VARCHAR,
    op VARCHAR,
    run_id VARCHAR,
    epoch BIGINT,
    activated_stake_lamports BIGINT,
    commission_percentage BIGINT
);
