# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: doublezero-eosagent

monorepo:
  tag_prefix: agent/
  dir: controlplane/agent

builds:
  - id: doublezero-eosagent
    main: cmd/eosagent/main.go
    binary: doublezero-eosagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: eosagent_archive
    format: tar.gz
    builds:
      - eosagent
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: doublezero-eosagent
    package_name: doublezero-eosagent
    builds:
      - doublezero-eosagent
    vendor: doublezero
    homepage: doublezero.xyz
    maintainer: nik <nik@malbeclabs.com>
    description: |-
      DoubleZero eosagent
    license: Apache 2.0
    formats:
      - rpm
    bindir: /usr/local/bin
    release: "1"
    section: default

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malbeclabs
    name: doublezero
  draft: true
  replace_existing_artifacts: true

announce:
  slack:
    enabled: true
    message_template: "DoubleZero EOS Agent {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#bots"

cloudsmiths:
  - organization: malbeclabs
    repository: doublezero
    distributions:
      deb: "any-distro/any-version"
      rpm: "any-distro/any-version"
