#!/bin/bash
# Generate ygot Go structs from OpenConfig YANG models
#
# Run this script from the generate/ directory:
#   ./generate.sh
#
# Or from anywhere:
#   telemetry/gnmi-writer/pkg/gnmi/oc/generate/generate.sh
#
# This generates Go structs from OpenConfig YANG models at v5.4.0:
# - openconfig-network-instance (includes ISIS, BGP, routing)
# - openconfig-interfaces
# - openconfig-system
# - openconfig-platform (components)
# - openconfig-platform-transceiver (optical transceiver state)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$(dirname "$SCRIPT_DIR")"

echo "Building ygot generator image..."
docker build -t ygot-generator -f "$SCRIPT_DIR/Dockerfile" "$SCRIPT_DIR"

echo "Running generator..."
# Use docker run with cat to output, since volume mounts may not work in all environments
docker run --rm ygot-generator sh -c "generator \
  -output_file=/out/oc.go \
  -package_name=oc \
  -generate_fakeroot \
  -fakeroot_name=Device \
  -compress_paths=false \
  -shorten_enum_leaf_names \
  -typedef_enum_with_defmod \
  -trim_enum_openconfig_prefix \
  -generate_simple_unions \
  -include_schema \
  -exclude_modules=ietf-interfaces \
  -path=/yang/public/release/models,/yang/public/release/models/types,/yang/public/third_party/ietf \
  /yang/public/release/models/network-instance/openconfig-network-instance.yang \
  /yang/public/release/models/interfaces/openconfig-interfaces.yang \
  /yang/public/release/models/system/openconfig-system.yang \
  /yang/public/release/models/platform/openconfig-platform.yang \
  /yang/public/release/models/platform/openconfig-platform-transceiver.yang \
  && cat /out/oc.go" > "$OUT_DIR/oc.go"

echo "Adding generated file header..."
{ echo "// Code generated by ygot. DO NOT EDIT."; echo ""; cat "$OUT_DIR/oc.go"; } > "$OUT_DIR/oc.go.tmp"
mv "$OUT_DIR/oc.go.tmp" "$OUT_DIR/oc.go"

echo "Running gofmt on generated code..."
gofmt -w "$OUT_DIR/oc.go"

echo "Done! Generated: $OUT_DIR/oc.go"
echo "File size: $(wc -l < "$OUT_DIR/oc.go") lines"
