#!/usr/bin/env bash
set -euo pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
workspace_dir=$(dirname "${script_dir}")

go run "${workspace_dir}/e2e/cmd/dzctl/main.go" "$@"
