FROM ghcr.io/malbeclabs/ceos:4.33.1F

ARG CONFIG

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz

RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz

COPY controlplane ./controlplane

# RUN  /usr/local/go/bin/go mod download

RUN CGO_ENABLED=0 GOOS=linux /usr/local/go/bin/go build -o doublezero-eosagent ./controlplane/cmd/eosagent/main.go

RUN cp doublezero-eosagent /mnt/flash/.

RUN cp $CONFIG /mnt/flash/startup-config

ENV INTFTYPE=eth
ENV ETBA=1
ENV SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
ENV CEOS=1 
ENV EOS_PLATFORM=ceoslab
ENV container=docker

CMD ["/sbin/init", "systemd.setenv=INTFTYPE=eth", "systemd.setenv=ETBA=1", "systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1", "systemd.setenv=CEOS=1", "systemd.setenv=EOS_PLATFORM=ceoslab", "systemd.setenv=container=docker", "systemd.setenv=MGMT_INTF=eth0"]
