[package]
name = "doublezero-activator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
eyre = "0.6.12"
tokio = { version = "1.43.0", features = ["full"] }
ipnetwork = "0.21.1"
bitvec = "1.0.1"
mockall = "^0.13"
solana-sdk = "1.18.26"
double-zero-sdk = { path = "../smartcontract/sdk/rs", version = "0.1.0" }
