[package]
name = "doublezero-activator"
version = "0.2.0"
edition = "2021"

[dependencies]
bitvec.workspace = true
chrono.workspace = true
clap.workspace = true
eyre.workspace = true
influxdb2.workspace = true
influxdb2-derive.workspace = true
influxdb2-structmap.workspace = true
ipnetwork.workspace = true
mockall.workspace = true
solana-sdk.workspace = true
tokio.workspace = true

# Dependencies from this workspace
doublezero_sdk.workspace = true
doublezero-sla-program.workspace = true

[dev-dependencies]

# Dependencies from this workspace
doublezero-sla-program.workspace = true
