[package]
name = "doublezero-activator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
eyre = "0.6.12"
tokio = { version = "1.44.2", features = ["full"] }
ipnetwork = "0.21.1"
bitvec = "1.0.1"

solana-sdk = "2.2.2"
doublezero_sdk = { path = "../smartcontract/sdk/rs", version = "0.1.0" }

[dev-dependencies]
doublezero-sla-program = { path = "../smartcontract/programs/dz-sla-program", version = "0.1.0" }
mockall = "^0.13"
