# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: doublezero-funder

monorepo:
  tag_prefix: funder/
  dir: controlplane/funder

builds:
  - id: doublezero-funder
    main: cmd/funder/main.go
    binary: doublezero-funder
    env:
      - CGO_ENABLED=0
    ldflags:
      -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: funder_archive
    formats: ['tar.gz']
    ids: [doublezero-funder]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: doublezero-funder
    package_name: doublezero-funder
    ids: [doublezero-funder]
    vendor: doublezero
    homepage: doublezero.xyz
    maintainer: dev <dev@malbeclabs.com>
    description: |-
      DoubleZero funder
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    release: "1"
    section: default
    contents:
      - src: controlplane/funder/cmd/doublezero-funder.service
        dst: /etc/systemd/system/doublezero-funder.service
    overrides:
      deb:
          scripts:
            postinstall: controlplane/packaging/scripts/funder/deb/postinstall.sh
            preremove: controlplane/packaging/scripts/funder/deb/preremove.sh
            postremove: controlplane/packaging/scripts/funder/deb/postremove.sh
      rpm:
          scripts:
            postinstall: controlplane/packaging/scripts/funder/rpm/postinstall.sh
            preremove: controlplane/packaging/scripts/funder/rpm/preremove.sh
            postremove: controlplane/packaging/scripts/funder/rpm/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malbeclabs
    name: doublezero
  draft: false
  replace_existing_artifacts: true

announce:
  slack:
    enabled: true
    message_template: "DoubleZero Funder {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#bots"

git:
  ignore_tags:
    - funder/daily

nightly:
  publish_release: true
  keep_single_release: true
  version_template: '{{ incpatch .Version }}~git{{ .Env.BUILD_DATE }}.{{ .ShortCommit }}'
  tag_name: 'funder/daily'
