# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: doublezero-internet-latency-collector

monorepo:
  tag_prefix: internet-latency-collector/
  dir: controlplane/internet-latency-collector

builds:
  - id: doublezero-internet-latency-collector
    main: cmd/collector/main.go
    binary: doublezero-internet-latency-collector
    env:
      - CGO_ENABLED=0
    ldflags:
      -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: collector_archive
    formats: ['tar.gz']
    ids: [doublezero-internet-latency-collector]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: doublezero-internet-latency-collector
    package_name: doublezero-internet-latency-collector
    ids: [doublezero-internet-latency-collector]
    vendor: doublezero
    homepage: doublezero.xyz
    maintainer: nik <nik@malbeclabs.com>
    description: |-
      DoubleZero network collector for internet latency measurements
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    release: "1"
    section: default
    contents:
      - src: controlplane/internet-latency-collector/cmd/collector/doublezero-internet-latency-collector.service
        dst: /etc/systemd/system/doublezero-internet-latency-collector.service
      - dst: /etc/doublezero-internet-latency-collector
        type: dir
        file_info:
          mode: 0755
      - src: controlplane/internet-latency-collector/cmd/collector/config.env
        dst: /etc/doublezero-internet-latency-collector/config.env
        type: config
        file_info:
          mode: 0640
          owner: root
          group: doublezero-collector
      - dst: /var/lib/doublezero-internet-latency-collector
        type: dir
        file_info:
          mode: 0755
          owner: doublezero-collector
          group: doublezero-collector
      - dst: /var/lib/doublezero-internet-latency-collector/state
        type: dir
        file_info:
          mode: 0755
          owner: doublezero-collector
          group: doublezero-collector
      - dst: /var/lib/doublezero-internet-latency-collector/output
        type: dir
        file_info:
          mode: 0755
          owner: doublezero-collector
          group: doublezero-collector
    overrides:
      deb:
          scripts:
            postinstall: controlplane/packaging/scripts/collector/deb/postinstall.sh
            preremove: controlplane/packaging/scripts/collector/deb/preremove.sh
            postremove: controlplane/packaging/scripts/collector/deb/postremove.sh
      rpm:
          scripts:
            postinstall: controlplane/packaging/scripts/collector/rpm/postinstall.sh
            preremove: controlplane/packaging/scripts/collector/rpm/preremove.sh
            postremove: controlplane/packaging/scripts/collector/rpm/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malbeclabs
    name: doublezero
  draft: false
  replace_existing_artifacts: true

announce:
  slack:
    enabled: true
    message_template: "DoubleZero Internet Latency Collector {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#bots"

git:
  ignore_tags:
    - collector/daily