# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: doublezero-activator

monorepo:
  tag_prefix: activator/

builds:
  - id: doublezero-activator
    binary: doublezero-activator
    builder: rust
    tool: cargo
    command: build
    flags:
      - --package=doublezero-activator
      - --release
    targets:
      - x86_64-unknown-linux-gnu
    env:
      - RUSTFLAGS=-C linker=x86_64-linux-gnu-gcc

archives:
  - id: activator_archive
    formats: ['tar.gz']
    ids: [activator]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: doublezero-activator
    package_name: doublezero-activator
    ids: [doublezero-activator]
    vendor: doublezero
    homepage: doublezero.xyz
    maintainer: steve <steve@malbeclabs.com>
    description: |-
      DoubleZero activator
    license: Apache 2.0
    formats:
      - deb
    bindir: /usr/local/bin
    release: 1
    section: default
    contents:
      - src: activator/doublezero-activator.service
        dst: /etc/systemd/system/doublezero-activator.service
    overrides:
      deb:
          scripts:
            postinstall: activator/packaging/scripts/deb/postinstall.sh
            preremove: activator/packaging/scripts/deb/preremove.sh
            postremove: activator/packaging/scripts/deb/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malbeclabs
    name: doublezero
  draft: false
  replace_existing_artifacts: true

announce:
  slack:
    enabled: true
    message_template: "DoubleZero Activator {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#bots"

git:
  ignore_tags:
    - activator/daily

nightly:
  publish_release: true
  keep_single_release: true
  version_template: '{{ incpatch .Version }}~git{{ .Env.BUILD_DATE }}.{{ .ShortCommit }}'
  tag_name: 'activator/daily'
