# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: doublezero

monorepo:
  tag_prefix: client/

builds:
  - id: doublezerod
    main: client/doublezerod/cmd/doublezerod/main.go
    binary: doublezerod
    env:
      - CGO_ENABLED=0
    ldflags:
      -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
  - id: doublezero-cli
    builder: rust
    tool: cargo
    binary: doublezero
    targets:
      - x86_64-unknown-linux-gnu
    command: build
    flags:
      - --package=doublezero
      - --release
    env:
      - RUSTFLAGS=-C linker=x86_64-linux-gnu-gcc
      - BUILD_VERSION={{.Version}}

archives:
  - id: doublezero_archive
    formats: ['tar.gz']
    ids: [doublezero-cli, doublezerod]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: doublezero
    package_name: doublezero
    ids: [doublezerod, doublezero-cli]
    vendor: doublezero
    homepage: doublezero.xyz
    maintainer: steve <steve@malbeclabs.com>
    description: |-
      DoubleZero client and cli
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    dependencies:
      - doublezero-solana
    contents:
      - src: client/doublezerod/cmd/doublezerod/doublezerod.service
        dst: /usr/lib/systemd/system/doublezerod.service
    deb:
      predepends:
        - adduser
    overrides:
      deb:
          scripts:
            postinstall: client/packaging/scripts/doublezerod/deb/postinstall.sh
            preremove: client/packaging/scripts/doublezerod/deb/preremove.sh
            postremove: client/packaging/scripts/doublezerod/deb/postremove.sh
      rpm:
          scripts:
            postinstall: client/packaging/scripts/doublezerod/rpm/postinstall.sh
            preremove: client/packaging/scripts/doublezerod/rpm/preremove.sh
            postremove: client/packaging/scripts/doublezerod/rpm/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malbeclabs
    name: doublezero
  draft: false
  replace_existing_artifacts: true

announce:
  slack:
    enabled: true
    message_template: "DoubleZero {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#bots"

git:
  ignore_tags:
    - client/daily

nightly:
  publish_release: true
  keep_single_release: true
  version_template: '{{ incpatch .Version }}~git{{ .Env.BUILD_DATE }}.{{ .ShortCommit }}'
  tag_name: 'client/daily'
