# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

includes:
  - from_file:
      path: .goreleaser.base.controller.yaml

cloudsmiths:
  - organization: malbeclabs
    repository: doublezero-devnet
    distributions:
      deb: "any-distro/any-version"
      rpm: "any-distro/any-version"
