name: qa.testnet

on:
  workflow_call:
  workflow_dispatch:

jobs:
  qa:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - run: go test -v e2e/qa_test.go -run TestConnectivityUnicast --args -hosts=nyc-tn-qa01,sfo-tn-qa01,fra-tn-qa01,sgp-tn-qa01 -env testnet
