name: release.devnet.internet-latency-collector.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: internet-latency-collector
      playbook: playbooks/internet_latency_collectors.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
