name: releaser.doublezero.monitor.tool

on:
  push:
    tags:
      - "doublezero-monitor-tool/v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#doublezero-monitor-tool/}" >> $GITHUB_OUTPUT
      - name: Checkout doublezero_monitor repo
        uses: actions/checkout@v4
        with:
          repository: alexpyattaev/doublezero_monitor
          path: doublezero_monitor
          ref: ${{ steps.get_version.outputs.VERSION }}
      - name: install dependencies for rpm packaging
        run: |
          sudo apt update
          sudo apt-get install squashfs-tools rpm -y
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          args: release -f release/.goreleaser.testnet.doublezero.monitor.tool.yaml --clean
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOTS_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
