name: release.client.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: client
    secrets: inherit
    permissions:
      contents: write
      packages: write
