name: release.devnet.all.daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'  # Every weekday at 10AM ET/9AM CT

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    strategy:
      matrix:
        component: [
          agent,
          controller,
          activator,
          client,
        ]
    with:
      component: ${{ matrix.component }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
