name: release.devnet.qa.agent.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: qa-agent
      playbook: playbooks/validators.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
