name: release.devnet.smartcontract.daily

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04-16c-64gb
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90
      - uses: Swatinem/rust-cache@v2
      - name: Install agave solana tools
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.3.6/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Set up keypairs
        run: |
          echo "${{ secrets.DEVNET_KEYPAIR }}" > id.json
          echo "${{ secrets.DEVNET_SERVICEABILITY_PROGRAM_KEYPAIR }}" > serviceability-program-keypair.json
          echo "${{ secrets.DEVNET_TELEMETRY_PROGRAM_KEYPAIR }}" > telemetry-program-keypair.json
      - name: Set solana devnet configuration
        run: |
          solana config set \
            --url https://doublezerolocalnet.rpcpool.com/8a4fd3f4-0977-449f-88c7-63d4b0f10f16 \
            --ws wss://doublezerolocalnet.rpcpool.com/8a4fd3f4-0977-449f-88c7-63d4b0f10f16/whirligig
          solana balance -k id.json
      - name: Build serviceability program
        run: |
          cargo build-sbf
        working-directory: smartcontract/programs/doublezero-serviceability
      - name: Deploy serviceability program to DevNet
        run: |
          solana program deploy \
            --program-id serviceability-program-keypair.json \
            -k id.json \
            target/deploy/doublezero_serviceability.so
      - name: Build telemetry program
        run: |
          cargo build-sbf --features devnet
        working-directory: smartcontract/programs/doublezero-telemetry
      - name: Deploy telemetry program to DevNet
        run: |
          solana program deploy \
            --program-id telemetry-program-keypair.json \
            -k id.json \
            target/deploy/doublezero_telemetry.so
