name: release.devnet.qa.agent.daily

on:
  workflow_dispatch:
    inputs:
      infra_branch:
        description: 'Branch of malbeclabs/infra to use for ansible playbooks'
        required: false
        type: string
        default: ''

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: qa-agent
      playbook: playbooks/qa_agents.yml
      infra_branch: ${{ inputs.infra_branch }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
