name: release.devnet.funder.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: funder
      playbook: playbooks/funder.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
