name: release.devnet.all.daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'  # Every weekday at 10AM ET/9AM CT

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    strategy:
      matrix:
        include:
          - component: agent
            playbook: playbooks/agents.yml
          - component: activator
            playbook: playbooks/activators.yml
          - component: controller
            playbook: playbooks/controllers.yml
          - component: funder
            playbook: playbooks/funders.yml
          - component: client
            playbook: playbooks/validators.yml
          - component: device-telemetry-agent
            playbook: playbooks/device_telemetry_agent.yml
          - component: internet-latency-collector
            playbook: playbooks/internet_latency_collectors.yml
          - component: qa-agent
            playbook: playbooks/qa_agents.yml
    with:
      component: ${{ matrix.component }}
      playbook: ${{ matrix.playbook }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
  smartcontract:
    uses: ./.github/workflows/release.devnet.smartcontract.daily.yml
    secrets: inherit
  qa:
    uses: ./.github/workflows/qa.devnet.yml
    needs:
      - release
      - smartcontract
  notify:
    name: Post failure to slack
    runs-on: ubuntu-24.04-16c-64gb
    needs:
      - release
      - smartcontract
      - qa
    if: failure()
    steps:
      - uses: malbeclabs/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_USERNAME: Doublezero Releaser
          SLACK_TITLE: Daily Release Failure
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
