name: daily

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  release:
    name: ${{ inputs.component }}
    runs-on: ubuntu-24.04-16c-64gb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: Swatinem/rust-cache@v2
      - name: Set env vars
        run: ./scripts/env.sh >> $GITHUB_ENV
      - name: install rust for cli
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: install dependencies for rpm packaging
        run: |
          sudo apt update
          sudo apt-get install squashfs-tools rpm gcc-x86-64-linux-gnu -y
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          args: release -f .goreleaser.${{ inputs.component }}.yaml --clean --skip cloudsmith --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
