name: release.devnet.all.daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'  # Every weekday at 10AM ET/9AM CT

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    strategy:
      matrix:
        include:
          - component: agent
            playbook: playbooks/agents.yml
          - component: activator
            playbook: playbooks/activators.yml
          - component: controller
            playbook: playbooks/controllers.yml
          - component: client
            playbook: playbooks/validators.yml
    with:
      component: ${{ matrix.component }}
      playbook: ${{ matrix.playbook }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
  smartcontract:
    uses: ./.github/workflows/release.devnet.smartcontract.daily.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write