name: release.devnet.smartcontract.daily

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04-16c-64gb
    container:
      image: ghcr.io/malbeclabs/doublezero-base:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up keypairs
        run: |
          echo "${{ secrets.DEVNET_KEYPAIR }}" > id.json
          echo "${{ secrets.DEVNET_SERVICEABILITY_PROGRAM_KEYPAIR }}" > serviceability-program-keypair.json
          echo "${{ secrets.DEVNET_TELEMETRY_PROGRAM_KEYPAIR }}" > telemetry-program-keypair.json
      - name: Set solana devnet configuration
        run: |
          solana config set \
            --url https://doublezerolocalnet.rpcpool.com/f50e62d0-06e7-410e-867e-6873e358ed30 \
            --ws wss://doublezerolocalnet.rpcpool.com/f50e62d0-06e7-410e-867e-6873e358ed30/whirligig
          solana balance -k id.json
      - name: Build serviceability program
        run: |
          cargo build-sbf
        working-directory: smartcontract/programs/doublezero-serviceability
      # - name: Deploy serviceability smart contract to DevNet
        # run: |
          # solana program deploy \
            # --program-id /root/.config/ops/serviceability-program-keypair.json \
            # -k /home/ubuntu/.config/doublezero/id.json \
            # targets/deploy/doublezero_serviceability.so
      - name: Build telemetry program
        run: |
          SERVICEABILITY_PROGRAM_ID=devnet cargo build-sbf
        working-directory: smartcontract/programs/doublezero-telemetry
      - name: Deploy telemetry program to DevNet
        run: |
          solana program deploy \
            --program-id telemetry-program-keypair.json \
            -k id.json \
            target/deploy/doublezero_telemetry.so