name: release.devnet.controller.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: controller
      playbook: playbooks/controllers.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
