name: releaser.agent

on:
  push:
    tags:
      - "agent/v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-24.04-16c-64gb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Set env vars
        run: ./scripts/env.sh >> $GITHUB_ENV
      - name: install dependencies for rpm packaging
        run: |
          sudo apt update
          sudo apt-get install squashfs-tools rpm -y
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          args: release -f .goreleaser.agent.yaml --clean
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOTS_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
