name: release.devnet.monitor.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: monitor
      playbook: playbooks/monitors.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
