name: release.devnet.agent.daily

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.daily.yml
    with:
      component: agent
      playbook: playbooks/agents.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
