name: Spellcheck

on:
  pull_request:
  push:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spellcheck
        run: make spellcheck
