pub const LAMPORTS_PER_SOL: u64 = 1_000_000_000;
pub const SOLANA_MAINNET_RPC_URL: &str = "https://api.mainnet-beta.solana.com";

pub const CITY_CODES: [(&str, &str); 49] = [
    ("New York-US", "NYC"),
    ("Los Angeles-US", "LAX"),
    ("San Francisco-US", "SFO"),
    ("Chicago-US", "CHI"),
    ("Seattle-US", "SEA"),
    ("Miami-US", "MIA"),
    ("Dallas-US", "DFW"),
    ("Washington-US", "WAS"),
    ("Boston-US", "BOS"),
    ("Atlanta-US", "ATL"),
    ("London-GB", "LON"),
    ("Paris-FR", "PAR"),
    ("Berlin-DE", "BER"),
    ("Frankfurt-DE", "FRA"),
    ("Amsterdam-NL", "AMS"),
    ("Barcelona-ES", "BAR"),
    ("Madrid-ES", "MAD"),
    ("Rome-IT", "ROM"),
    ("Milan-IT", "MIL"),
    ("Singapore-SG", "SIN"),
    ("Tokyo-JP", "TYO"),
    ("Seoul-KR", "SEO"),
    ("Hong Kong-HK", "HKG"),
    ("Sydney-AU", "SYD"),
    ("Melbourne-AU", "MEL"),
    ("Toronto-CA", "YYZ"),
    ("Montreal-CA", "YUL"),
    ("Vancouver-CA", "YVR"),
    ("Mexico City-MX", "MEX"),
    ("São Paulo-BR", "SAO"),
    ("Buenos Aires-AR", "BUE"),
    ("Mumbai-IN", "BOM"),
    ("Delhi-IN", "DEL"),
    ("Bangalore-IN", "BLR"),
    ("Dubai-AE", "DXB"),
    ("Tel Aviv-IL", "TLV"),
    ("Moscow-RU", "MOW"),
    ("Stockholm-SE", "STO"),
    ("Copenhagen-DK", "CPH"),
    ("Oslo-NO", "OSL"),
    ("Warsaw-PL", "WAW"),
    ("Prague-CZ", "PRG"),
    ("Vienna-AT", "VIE"),
    ("Zurich-CH", "ZRH"),
    ("Dublin-IE", "DUB"),
    ("Helsinki-FI", "HEL"),
    ("Lisbon-PT", "LIS"),
    ("Athens-GR", "ATH"),
    ("Istanbul-TR", "IST"),
];
